version: "3.8"

services:
  django:
    build: .
    container_name: django
    command: >
      sh -c "python3 manage.py migrate &&
            python3 manage.py runserver 0.0.0.0:8000"
        
    volumes:
      - .:/usr/src/base/
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - DB_HOST=pgdb
      - DB_NAME=pgdb
      - DB_USER=postgres
      - DB_PASSWORD=postgres

    depends_on:
      - pgdb
      - redis
  celery:
    build: .
    command: celery -A SPTodoList worker -l INFO
    volumes:
      - .:/usr/src/base/
    depends_on:
      - django
      - redis
  pgdb:
    image: postgres
    container_name: pgdb
    environment:
      - POSTGRES_DB=pgdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgres/data/
  redis:
    image: "redis:alpine"

volumes:
  pgdata: